run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - revive

linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: blank-imports
      - name: indent-error-flow